services:
  - type: web
    runtime: docker
    name: securegalleryvault-shared-yogesh-2026
    plan: starter
    region: oregon
    dockerfilePath: ./SecureGalleryVault.SharedServer/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: SGV_DATA_DIR
        value: /var/data/sgv-shared
      - key: SGV_BOOTSTRAP_CODE
        value: 78421592
      - key: SGV_MASTER_SECRET
        generateValue: true
    disk:
      name: sgv-shared-data
      mountPath: /var/data
      sizeGB: 1
